#!/bin/sh
#
# by Shane Zatezalo Lottadot LLC http://lottadot.com/
# A script to create a remote branch on the 'origin' repository and then create 
# a local branch that tracks the remote branch on the 'origin' repository.
# then checkout this new branch on the local FS.
#
# when done working on the branch, after you have committed and pushed you can
#
# merge the branch into origin's master
#  git co master
#  git merge branch_name
#
# delete the branch:
#
#  git branch -r -d origin/branch_name
#
# usage: git-create-branch <branch_name>
#
# based on info from
# http://www.zorched.net/2008/04/14/start-a-new-branch-on-your-remote-git-repository/ 
#

if [ $# -ne 1 ]; then
         echo 1>&2 Usage: $0 branch_name
         exit 127
fi
 
branch_name=$1
git push origin master:refs/heads/$branch_name
echo "git push origin master:refs/heads/$branch_name"
git fetch origin
git checkout --track -b $branch_name origin/$branch_name
git pull
