#!/bin/sh
#
# by Shane Zatezalo Lottadot LLC http://lottadot.com/
#
if [ $# -ne 1 ]; then
         echo 1>&2 Usage: $0 branch_name
         exit 127
fi
 
branch_name=$1
git fetch origin
git checkout --track -b $branch_name origin/$branch_name
git pull
